### ISSUE TITLE
Handle config file permissions

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-skill-utils#254]
## Issue
Current implementation does not account for config directory having insufficient read/write permissions. Containers will often mount external configuration as read-only and this should be handled in some way.

## Todo
- [x] Add methods to determine file permissions
- [x] Fallback to some directory if requested one can't be accessed
- [x] Handle reading/relocating configuration files that are readable but not writable

## Other Considerations
- Should relocating configuration be optional?  (Initial implementation I think not, possible future task)
- What if the default location also has config; is it overwritten, updated, used?
- Should migration be handled for any config object, or just "known" config (local, user, auth) (Initial implementation this can be handled in the helper methods only)
- Should Read-Only be an optional config flag? (Worth a separate issue to add read-only config if desired)

**Comment by NeonDaniel** [comment]
#251
